spring:
  application:
    name: notificacao

  mail:
    host: smtp.gmail.com #Servidor SMTP do Gmail.
    port: 587 #SMTP com STARTTLS (seguro)
    username:
      #e-mail remetente
    password:
      #senha de app
    protocol: smtp #Define o protocolo de envio.

    #Isso aqui é o que o JavaMailSender usa por baixo.

    properties:
      mail:
        smtp:
          auth: true
          #Obriga autenticação.
          starttls:
            enable: true #Ativa criptografia TLS (sem isso o Gmail bloqueia).

          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          #Evita que a aplicação: trave, fique esperando eternamente

          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

  thymeleaf:
    enabled: true
    #Diz pro Spring: “Pode usar templates HTML”
    #Isso permite: templateEngine.process("notificacao", context);

envio:
  email:
    remetente:
    nomeRemetente: 'Kristian'

server:
  port: 8082